### ISSUE TITLE
Proposal: Be more consistent with the version of NumPy we are using to build wheels

### ISSUE THREAD

**Issue by ostueker** [ComputeCanada/software-stack#104]
I think we should be a bit more systematic about the version of numpy we load to build compile other wheels.
I propose the following:

* Instead of our build_wheel.sh to install the latest version of numpy, scipy and cython (`PYTHON_DEPS_DEFAULT="numpy scipy cython"`) it should simply the latest `scipy-stack`.
* The `scipy-stack` should export a variable that contains the version of numpy that's used. (e.g. `$NUMPYVERSION` )
* Then we use `manipulate_wheels.py --update_req "numpy>=${NUMPYVERSION}"`  to mark the wheel which numpy version has been used and is therefore the oldest version that is deemed to be compatible with this wheel.  
  (maybe just for wheels that have C-extensions, which we can identify because they are Python version specific; I don't think it's easy to determine whether it's actually linked against the numpy lib, or am I wrong)
* We'll commit to a semi regular schedule for building new scipy-stacks, e.g. once per year.  
  Right now 1.22.1 is out, however I would suggest to base a scipy-stack/2022a on numpy-1.21.5  which is the final 1.21.x release.   
  We can still add the latest numpy to the wheelhouse, but I'd rather be more conservative than building (testing) all wheels with that version.

Thoughts? Ideas? Comments?

**Comment by mboisson** [comment]
I would not load the module, because it comes with a lot more than just numpy, scipy, cython. 
We could use a requirement file with pinned version however.

**Comment by mboisson** [comment]
Another caveat is that `>=` is not always true, like for TensorFlow, so I don't think we want to automatically update requirements to specify a minimum version of `numpy`. Or at least, we need an exception mechanism.

**Comment by mboisson** [comment]
> Yes, we need a way to handle this. We should not override that version-spec but extend it. So we should turn a `numpy<1.22.0` into `numpy>=1.21.2,<1.22.0` for example.

But that could end up with `numpy>=1.21.2,<=1.19.5`

**Comment by ostueker** [comment]
No, because the build would fail ;-)

**Comment by mboisson** [comment]
Fair enough. 

I'm not against the idea (other than using the `scipy-stack` module, and therefore we need to get the version of `numpy` from another source, maybe by grepping a `requirements.txt` file, or querying the build virtualenv). 

Do you want to work on a PR for this ?

**Comment by ostueker** [comment]
Yes, I think I'll give it a go.

**Comment by ccoulombe** [comment]
I think this will lead to more issues with the dependency hell. 
I don't think we should try to fix hell. We can try to be more consistent, but some packages requires very specific versions and in those cases we could either have a PR upstream or use the asked version.

**Comment by ccoulombe** [comment]
We could pin the numpy version in the build wheel ? And update it or use the version from the config to overwrite it when needed

**Comment by ostueker** [comment]
Yes, I was thinking to effectively do something like this (`PYTHON_DEPS_DEFAULT`), but once you need to use an older version of numpy,  you run into a problem:

How to you find which version of a package can be used with that older numpy?

And how do you do this for a list of 20, 30 packages of which a subset of 5-10 are sensitive to the numpy version, not even knowing which packages fall into that category or not.  SciPy, Pandas and Matplotlib for sure, but what else?

**Comment by ostueker** [comment]
I'm currently experimenting with dumping the packages from the build-venv into a json file (`pip list --local --format=json > build_env.json`) and whether we can add that to the `*.dist-info` subdirectory of the wheel.

This way we can at least record the state of the build environment and generate a table at a later time.

**Comment by ostueker** [comment]
Okay, my commit in ComputeCanada/wheels_builder@f3b4c16d29b511cbf476d83c0248c70c5e0dc192  now adds a file `build_env.json` to the package's .dist-info directory that contains the packages present in the build-environment after the build.

e.g.:
```json
//$ cat build_env.json | json_pp 
[
   {
      "name" : "Cython",
      "version" : "0.29.27+computecanada"
   },
   {
      "name" : "numpy",
      "version" : "1.21.2+computecanada"
   },
   {
      "name" : "pip",
      "version" : "21.2.3+computecanada"
   },
   {
      "name" : "scipy",
      "version" : "1.7.3+computecanada"
   },
   {
      "name" : "setuptools",
      "version" : "57.4.0+computecanada"
   },
   {
      "name" : "wheel",
      "version" : "0.37.0+computecanada"
   }
]
```

**Comment by ostueker** [comment]
We could also expand the data-model and also store the username and a timestamp when the wheel was built.

**Comment by mboisson** [comment]
What are the guidelines about adding custom metadata into wheels ? 

Also, how will this metadata be useful at scale ? It is costly to query stuff that is embedded into wheels.

**Comment by ostueker** [comment]
We could extract that data and store it in a bigger data-structure along with the absolute path of the wheel and have "avail_wheels" display the associated numpy version (if numpy is also listed as a dependency).

We don't need to rebuild the whole index every time, but can restrict it to extract it from wheels that are not yet present or in case the timestamp has changed.

I think it's better to capture a bit more metadata that we'll actually need rather than not capturing it and later on wishing we had.

**Comment by mboisson** [comment]
🤔 Starting to sound like a really over-engineered solution. What is the root cause of the problem you are trying to solve ?

**Comment by ccoulombe** [comment]
avail_wheel will not parse any wheels metadata. Some wheels are 2GB in size and takes 30s or more to extract.

Does `manipulate_wheel` accept the presence of other files in the wheel metadata? Some tools might actually raise on this.

**Comment by ostueker** [comment]
> What is the root cause of the problem you are trying to solve ?

Being able to find (filter) versions of packages that can be used with a particular version of numpy.

Usecase: I have this user that wants to use a package that needs tensorflow 2.5.x and therefore needs numpy <1.20.0
How do I find versions of scipy, pandas, matplotlib, etc that can work with numpy 1.19.5 (or 1.19.2)

And those packages are not the only ones that are sensitive to the numpy version.  

I don't even know whether there is a way to figure out which version of numpy a wheel is compatible with.
The next best thing is to record the version it was built against.

> Does manipulate_wheel accept the presence of other files in the wheel metadata? Some tools might actually raise on this.

Yes, in fact have expanded manipulate_wheel to add the JSON file into the dist-info directory inside the wheel.

https://github.com/ComputeCanada/wheels_builder/commit/f3b4c16d29b511cbf476d83c0248c70c5e0dc192#diff-a1943f81ea0477717b3a0f3cd66d06a29e5e0f51b05ed6464d9fbd37c507b4baR105-R114

**Comment by ostueker** [comment]
> the checksum would need to be added to the RECORD as well.
That's done by `wf2.write_distinfo()`

**Comment by mboisson** [comment]
If it's not going to be helpful without an index, why put it in the wheel in the first place ? Maybe we should just generate a json index and append to it ?

**Comment by ostueker** [comment]
> avail_wheel will not parse any wheels metadata. Some wheels are 2GB in size and takes 30s or more to extract. Even parsing only one specific file from the wheel would slow considerably.

Yes, and that's why I propose building up an external index.

> If it's not going to be helpful without an index, why put it in the wheel in the first place ? 

But the nice thing of having the metadata (and more that we need) inside the wheel is, that we can re-create the index if we want and at that time add additional data to it.
But in order to do so, we need to capture the data before it's gone for good.

Keeping the index lean (only storing the data that is actually needed) helps keep the performance of avail_wheels high.

I'm thinking the index could be updated similar to the mii index.

>Starting to sound like a really over-engineered solution.

Over-engineered? Sure.

**Comment by mboisson** [comment]
> > What is the root cause of the problem you are trying to solve ?
> 
> Being able to find (filter) versions of packages that can be used with a particular version of numpy.
> 
> Usecase: I have this user that wants to use a package that needs tensorflow 2.5.x and therefore needs numpy <1.20.0 How do I find versions of scipy, pandas, matplotlib, etc that can work with numpy 1.19.5 (or 1.19.2)
> 
> And those packages are not the only ones that are sensitive to the numpy version.
> 
> I don't even know whether there is a way to figure out which version of numpy a wheel is compatible with. The next best thing is to record the version it was built against.


We don't need to be able to figure it out ourselves, we need pip to figure it out itself. That's going to happen if we adjust the requirements correctly. 

Adjusting the requirements of a binary wheel that links against the numpy ABI and requires a specific version should be all that's needed, and is the real solution in my opinion. 

Can you extract a handful of the problematic wheels and see what the shared objects are linking against and which would be in numpy ? We can then write some logic to detect that and adjust wheel requirements accordingly.

**Comment by mboisson** [comment]
> I think this will lead to more issues with the dependency hell. I don't think we should try to fix hell nor play in the gardens of pip. We can try to be more consistent, but some packages requires very specific versions and in those cases we could either have a PR upstream or use the asked version.

To answer to @ccoulombe here, updating the requirements is not leading to more issues, it is merely documenting the issues such that pip can hopefully find a working combination when it searches for requirements.

**Comment by ostueker** [comment]
> Can you extract a handful of the problematic wheels and see what the shared objects are linking against and which would be in numpy ?

That's exactly the challenging part and the crux behind all of this.

I have a reproducible recipe that produces a venv that is extremely challenging to resolve:


```console
$ module purge 
$ module load python/3.8
$ virtualenv --no-download venv
$ source venv/bin/activate
(venv) $ pip install --no-index -r requirements.txt 
(venv) $ python test_obspy.py 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "test_obspy.py", line 1, in <module>
    from obspy import read
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/obspy/__init__.py", line 44, in <module>
    from obspy.core.event import read_events, Catalog
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/obspy/core/event/__init__.py", line 30, in <module>
    from .catalog import Catalog, read_events
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/obspy/core/event/catalog.py", line 35, in <module>
    from obspy.imaging.cm import obspy_sequential
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/obspy/imaging/cm.py", line 211, in <module>
    from matplotlib.cm import get_cmap
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/matplotlib/rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/matplotlib/colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/matplotlib/scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/matplotlib/ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "/gpfs/scratch/stuekero/pywheel_test/venv/lib/python3.8/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

Here we see that `matplotlib` is clearly a trouble maker.  But which other packages play into this as well?

```console
(venv) $ pip list  | wc -l
125
```
There are more than a hundred of them. Two lines of header and probably a handful that we can quickly rule out. 
But what about the rest of them?

requirements.txt:
```
pytest
numpy~=1.19.2
keyring>=15.1
pkginfo>=1.4.2
scipy>=1.4.1
tensorflow~=2.5.0
keras~=2.3.1
matplotlib
pandas
tqdm>=4.48.0
h5py~=3.1.0
obspy
jupyter 
```

test_obspy.py
```python
from obspy import read
st = read()  # load example seismogram
st.filter(type='highpass', freq=3.0)
st = st.select(component='Z')
st.plot(outfile='seismogram.png')
```

Tip: the procedure works, if `scipy-stack/2020b` loaded before the creation of the venv.

Having the build_env.json included in the wheels, would also mean that I could something like:
```
$ grep  numpy $VIRTUAL_ENV/lib/python3.8/site-packages/*.dist-info/build_env.json
```
to identify candidates.

**Comment by mboisson** [comment]
`find -name '*.so' -print0 | xargs -0 ldd | grep numpy` ?

**Comment by ostueker** [comment]
The .so's are statically linked, so no `ldd`. (at least all the .so's in the matplotlib that I've tried yesterday).

**Comment by mboisson** [comment]
Ok, we can use another trick then. Here is the list of packages that are affected, from the packages installed by your `requirements.txt`: 

```
grep -l "module compiled against API version" $(find . -name '*.so') | cut -d'/' -f 5 | sort -u
h5py
matplotlib
numpy
pandas
scipy
tensorflow
``` 

So, at build time, we can grep for that string in the resulting wheel. If it is found, we need to pin the version of numpy in the requirements.

**Comment by mboisson** [comment]
Might contain useful information about which version to pin to ? https://numpy.org/devdocs/user/depending_on_numpy.html

**Comment by ostueker** [comment]
> So, at build time, we can grep for that string in the resulting wheel. If it is found, we need to pin the version of numpy in the requirements.

Yes, I think that's a good plan. 

> Might contain useful information about which version to pin to ?

Not really. This contains helpful information for developers of packages and some may adhere to the advice given (I'd expect major and well-managed projects will) but especially in the domain of scientific code it's a lot of "wild-west" mentality.

[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) provides some guidance on which versions of Python and Numpy should be supported until a given date and we can use this for our own decisions regarding when to drop support for a Python version and when to change the default for a numpy version.  
Though we can easily add at least another 6 months to the dates mentioned in NEP 29, as it is about the next release of the package after the date.   Until it percolates down to us building wheels, some time will have passed.

> We could also consider building against the oldest supported version of numpy ?

Yes. However, since we have already been building wheels against Numpy 1.21.x, we should continue to do so until it falls out of support.  Anything else would probably cause much more pain.

I was able to find a list of NumPy API versions alongside their release-versions:

```
# Minor API version.  This number is increased whenever a change is made to the
# C-API -- whether it breaks binary compatibility or not.  Some changes, such
# as adding a function pointer to the end of the function table, can be made
# without breaking binary compatibility.  In this case, only the C_API_VERSION
# (*not* C_ABI_VERSION) would be increased.  Whenever binary compatibility is
# broken, both C_API_VERSION and C_ABI_VERSION should be increased.
#
# 0x00000008 - 1.7.x
# 0x00000009 - 1.8.x
# 0x00000009 - 1.9.x
# 0x0000000a - 1.10.x
# 0x0000000a - 1.11.x
# 0x0000000a - 1.12.x
# 0x0000000b - 1.13.x
# 0x0000000c - 1.14.x
# 0x0000000c - 1.15.x
# 0x0000000d - 1.16.x
# 0x0000000d - 1.19.x
# 0x0000000e - 1.20.x
# 0x0000000e - 1.21.x
# 0x0000000f - 1.22.x
# 0x0000000f - 1.23.x
C_API_VERSION = 0x0000000f
```
https://github.com/numpy/numpy/blob/main/numpy/core/setup_common.py#L26-L48

The situation is not quite as bad as I expected, as for Python 3.8 we currently have numpy wheels between 1.16.4 to 1.21.2.  
This corresponds to API version `0xd` for NumPy 1.16.x  to 1.19.x and `0xe` for NumPy 1.20.x  and 1.21.x.

**Comment by mboisson** [comment]
It looks like they change ABI version every even minor version ? (i.e. it changes for 10, 12, 14, 16, ~18~, 20, 22). They skipped a change in ABI version from 16 to 10 however, so maybe this pattern is just coincidental.

**Comment by ostueker** [comment]
ABI or API version?

`C_ABI_VERSION = 0x01000009` hasn't changed between v1.16.0 and v1.22.0

https://github.com/numpy/numpy/blob/v1.16.0/numpy/core/setup_common.py#L26
https://github.com/numpy/numpy/blob/v1.22.0/numpy/core/setup_common.py#L24

**Comment by mboisson** [comment]
API, sorry
