### ISSUE TITLE
`avail_wheels` does not work inside a Python 2 environment

### ISSUE THREAD

**Issue by ofisette** [ComputeCanada/software-stack#115]
`avail_wheels` does not work if the `python` command points to a Python 2.x interpreter. This is because `avail_wheels/runtime_env.py` assumes that `python -V` prints to `stdout`. While this is the case for Python 3.x, 2.x used to print the version to `stderr`.

To reproduce:

```
[ofisette@gra-login1 ~]$ module purge
[ofisette@gra-login1 ~]$ module load python/2
[ofisette@gra-login1 ~]$ virtualenv $HOME/py2-env
[ofisette@gra-login1 ~]$ source $HOME/py2-env/bin/activate
(py2-env) [ofisette@gra-login1 ~]$ avail_wheels
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 483, in <module>
    main()
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 448, in main
    args = create_argparser().parse_args()
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 423, in create_argparser
    python_group.add_argument("-p", "--python", choices=env.available_pythons, nargs='+', default=[env.current_python] if env.current_python else env.available_pythons, help="Specify the python versions to look for."),
  File "/cvmfs/soft.computecanada.ca/custom/python/envs/avail_wheels/runtime_env.py", line 82, in current_python
    self._current_python = run("python -V", shell=True, capture_output=True).stdout.decode().split()[1]
IndexError: list index out of range
```

**Comment by ccoulombe** [comment]
Thanks for the bug report! Will have a better look soon as I am catching up weeks of information.

**Comment by ccoulombe** [comment]
This is fixed but not deployed yet. I am fixing 1-2 other bugs and will release version `2.0.1`

**Comment by mboisson** [comment]
Should this be closed ?
