### ISSUE TITLE
bug in `wheel_architecture.sh`

### ISSUE THREAD

**Issue by ostueker** [ComputeCanada/software-stack#24]
I have successfully unmanylinux'ed the Open3D 0.10.0.0 wheel with:
```console
$ unmanylinuxize.sh --package open3d --version 0.10.0.0                                                                            
[...]
'open3d-0.10.0.0-cp36-cp36m-linux_x86_64.whl' -> '../open3d-0.10.0.0-cp36-cp36m-linux_x86_64.whl'
'open3d-0.10.0.0-cp37-cp37m-linux_x86_64.whl' -> '../open3d-0.10.0.0-cp37-cp37m-linux_x86_64.whl'
'open3d-0.10.0.0-cp38-cp38-linux_x86_64.whl' -> '../open3d-0.10.0.0-cp38-cp38-linux_x86_64.whl'
```
and when I have the  `wheel_architecture.sh` guess the architecture, I get:

```console
$ wheel_architecture.sh open3d-0.10.0.0-cp37-cp37m-linux_x86_64.whl 
generic generic
```

Looks reasonable? 

Well, if (for example) I create a virtualenv from `module load StdEnv/2020 python/3.7.7`
and look at the ldd output everything looks just fine:

```console
(env37) $ ldd env37/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007fffbb0d9000)
        libGL.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/x86_64/libGL.so.1 (0x00002ab037c0b000)
        librt.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/librt.so.1 (0x00002ab037e97000)
        libdl.so.2 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libdl.so.2 (0x00002ab037ea1000)
        libX11.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libX11.so.6 (0x00002ab037ea6000)
        libstdc++.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libstdc++.so.6 (0x00002ab037fea000)
        libm.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libm.so.6 (0x00002ab038262000)
        libgomp.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libgomp.so.1 (0x00002ab0383a5000)
        libgcc_s.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libgcc_s.so.1 (0x00002ab0383dd000)
        libpthread.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libpthread.so.0 (0x00002ab0383f7000)
        libc.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libc.so.6 (0x00002ab038417000)
        /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/ld-linux-x86-64.so.2 (0x00002ab036e93000)
        libGLX.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/x86_64/libGLX.so.0 (0x00002ab0385d2000)
        libXext.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libXext.so.6 (0x00002ab038806000)
        libGLdispatch.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/x86_64/libGLdispatch.so.0 (0x00002ab03881b000)
        libxcb.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libxcb.so.1 (0x00002ab038ad1000)
        libXau.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libXau.so.6 (0x00002ab038afb000)
        libXdmcp.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libXdmcp.so.6 (0x00002ab038b00000)
        libbsd.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libbsd.so.0 (0x00002ab038b08000)
```

But if I start from `module load StdEnv/2018.3 python/3.7.4` and do the same, the GLIBC from NIX is clearly too old:

```console
(env374) $ ldd env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so 
env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6: version `GLIBC_2.27' not found (required by env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so)
        linux-vdso.so.1 (0x00007ffd4a599000)
        libGL.so.1 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libGL.so.1 (0x00002adb0fa4a000)
        librt.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/librt.so.1 (0x00002adb0fcd5000)
        libdl.so.2 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libdl.so.2 (0x00002adb0fedd000)
        libX11.so.6 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libX11.so.6 (0x00002adb100e1000)
        libstdc++.so.6 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libstdc++.so.6 (0x00002adb10421000)
        libm.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6 (0x00002adb107f8000)
        libgomp.so.1 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libgomp.so.1 (0x00002adb10afd000)
        libgcc_s.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libgcc_s.so.1 (0x00002adb10d33000)
        libpthread.so.0 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libpthread.so.0 (0x00002adb10f49000)
        libc.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6 (0x00002adb11166000)
        /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib64/ld-linux-x86-64.so.2 (0x00002adb0eb08000)
        libGLX.so.0 => /cvmfs/soft.computecanada.ca/nix/store/sxdgs7s7y6llk1ahzdca5nzwad482s7i-libglvnd-1.0.0/lib/libGLX.so.0 (0x00002adb11504000)
        libXext.so.6 => /cvmfs/soft.computecanada.ca/nix/store/jnwdijqqadn87kj4rv246pmascjlw2mv-libXext-1.3.3/lib/libXext.so.6 (0x00002adb11736000)
        libxcb.so.1 => /cvmfs/soft.computecanada.ca/nix/store/vlningalayif6h9jzdkzczhr1c17q84a-libxcb-1.12/lib/libxcb.so.1 (0x00002adb11948000)
        libXau.so.6 => /cvmfs/soft.computecanada.ca/nix/store/ipbqjzq1ljn2ca7j67mhvfsml46c5b5c-libXau-1.0.8/lib/libXau.so.6 (0x00002adb11b71000)
        libXdmcp.so.6 => /cvmfs/soft.computecanada.ca/nix/store/lfjsq4xyrh7vj14ilrkxccd7nqbnjava-libXdmcp-1.1.2/lib/libXdmcp.so.6 (0x00002adb11d75000)
        libGLdispatch.so.0 => /cvmfs/soft.computecanada.ca/nix/store/sxdgs7s7y6llk1ahzdca5nzwad482s7i-libglvnd-1.0.0/lib/libGLdispatch.so.0 (0x00002adb11f7b000)
```

```console
(env374) $ python -c "import open3d; print(open3d.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/open3d/__init__.py", line 47, in <module>
    from open3d.open3d_pybind import camera
ImportError: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6: version `GLIBC_2.27' not found (required by /home/stuekero/wheels/env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by mboisson** [comment]
Hi Oliver,
The `wheel_architecture.sh` script only checks for the paths in the rpath, not the actual compatibility. Given the dependency on a specific version of libm, you probably should put it in gentoo. 

Maxime

**Comment by mboisson** [comment]
I would not say it is a bug, but rather a limitation.
